apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: pvsa
  azurestorageaccountkey: tPMAJ6h0Rw9s4hgeV+jiknbyi2pR7yyEoLCt/E8r0p9wnwJytoCeUoeABNrZBHFHSvBtHjTKzz7Ez0n5jWY4tw==
